<?php
return array (
  '
transaction_pic_url' => '汇款凭证  ',
  'accepted_at' => '受理时间  ',
  'accepter' => '受理者  ',
  'accepter_id' => '受理者ID  ',
  'accept_acc_name' => '收款卡户名  ',
  'accept_card_num' => '收款卡卡号  ',
  'accept_email' => '收款卡email  ',
  'amount' => '申请充值金额  ',
  'auditor' => '审核者  ',
  'auditor_id' => '受理审核者ID  ',
  'bankcard_no' => '收款卡编号  ',
  'bank_id' => '用户发起充值的银行ID  ',
  'commission' => '佣金  ',
  'commission_sent_at' => '佣金发放时间  ',
  'created_at' => '记录添加时间  ',
  'error_msg' => '错误信息  ',
  'fee' => '实际返还手续费  ',
  'id' => '主键自增id  ',
  'ip' => '用户充值IP  ',
  'mode' => '收款方式：0其它，1 银行账号，2 Email  ',
  'order_no' => '平台订单号  ',
  'pay_time' => '用户汇款时间  ',
  'pic_submited_at' => '凭证提交时间  ',
  'postscript' => '附言  ',
  'put_at' => '加币时间  ',
  'service_bank_seq_no' => '银行流水号  ',
  'service_order_no' => '服务方订单号  ',
  'service_time' => '银行处理时间  ',
  'status' => '状态：0未处理（默认），1申请成功，2申请失败，3充值成功，4加币异常  ',
  'status_commission' => '佣金状态  ',
  'top_agent' => '总代用户名  ',
  'username' => '用户名  ',
  'user_forefather_ids' => '用户祖先ID序列  ',
  'user_id' => '用户ID  ',
  'verified_at' => '受理审核时间  ',
);