<?php
return array (
  'administrator' => '管理员',
  'amount' => '金额',
  'available' => '余额',
  'award-prize' => '派奖',
  'bet' => '投注',
  'bp_name' => '商户名称',
  'cancel-prize' => '撤销派奖',
  'create-success' => '荷包账变创建成功',
  'created_at' => '创建时间',
  'drop' => '撤单',
  'error-create-balance' => '荷包账变余额保存失败',
  'error-create-data' => '荷包账变数据错误',
  'error-on-saving' => '荷包账变保存失败',
  'load' => '充值',
  'serial_number' => '序列号',
  'type_name' => '账变类型',
  'withdraw' => '提现',
);